name: Build and Push Controller Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: lowercase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY@L}" >>${GITHUB_ENV}

      - name: Extract Chart version
        run: |
          if [ ! -f dist/chart/Chart.yaml ]; then
            echo "Chart.yaml not found" >&2
            exit 1
          fi
          VERSION_LINE=$(grep '^version:' dist/chart/Chart.yaml || true)
          if [ -z "$VERSION_LINE" ]; then
            echo "version not found in Chart.yaml" >&2
            exit 1
          fi
          VERSION=$(echo "$VERSION_LINE" | awk '{print $2}')
          echo "CHART_VERSION=$VERSION" >>${GITHUB_ENV}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: ghcr.io/${{ env.REPO }}/controller
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ghcr.io/${{ env.REPO }}/controller:${{ env.CHART_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}

